//funzione che calcola i quadrati di due numeri interi;
void quadrati(int &a, int &b);
void caricaVettore(int array[], int dim);
void visualizzaVettore(int array[], int dim);
//funzione che trova l'indice del valore più alto;
void indicemax(int array[], int dim, int &indice);
//funzione che somma tutti i nvalori di un array di interi;
void sommaArray(int array[], int dim, int &totale);
//funzione che conta il numero di consonanti in una stringa;
void contaCons(char stringa[], int &nCons);
//funzione che calcola l'equivalente binario di un numero e lo restituisce come stringa;
void binario(int num, char binario[]);